"""Add title column to stories

Revision ID: 7ec09a2ecc9d
Revises: ed1db52af70d
Create Date: 2025-12-27 06:30:22.774939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec09a2ecc9d'
down_revision: Union[str, Sequence[str], None] = 'ed1db52af70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'title')
    # ### end Alembic commands ###
