"""Add blacklisted_on column

Revision ID: ed1db52af70d
Revises: abc4a8c769b2
Create Date: 2025-12-19 12:24:41.229522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1db52af70d'
down_revision: Union[str, Sequence[str], None] = 'abc4a8c769b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('blacklisted_on', sa.DateTime(), nullable=True))
    op.drop_column('blacklisted_tokens', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('blacklisted_tokens', 'blacklisted_on')
    # ### end Alembic commands ###
